Modify .gitignore and add baseline ignored stuff
-- to help track what the patches do, and becuase the patches assume a
./configure-ed tree already
-- also I think the .gitignore is overly broad

diff --git a/po/Makefile b/po/Makefile
--- a/po/Makefile
+++ b/po/Makefile
@@ -61,10 +61,10 @@ MSGINIT = msginit
 MSGCONV = msgconv
 MSGFILTER = msgfilter
 
-POFILES = @POFILES@
-GMOFILES = @GMOFILES@
-UPDATEPOFILES = @UPDATEPOFILES@
-DUMMYPOFILES = @DUMMYPOFILES@
+POFILES = 
+GMOFILES = 
+UPDATEPOFILES = 
+DUMMYPOFILES = 
 DISTFILES.common = Makefile.in.in remove-potcdate.sin \
 $(DISTFILES.common.extra1) $(DISTFILES.common.extra2) $(DISTFILES.common.extra3)
 DISTFILES = $(DISTFILES.common) Makevars POTFILES.in \
@@ -72,10 +72,240 @@ $(POFILES) $(GMOFILES) \
 $(DISTFILES.extra1) $(DISTFILES.extra2) $(DISTFILES.extra3)
 
 POTFILES = \
+     ../alpine/osdep/termout.wnt.c \
+     ../alpine/osdep/termin.wnt.c \
+     ../alpine/osdep/termin.gen.c \
+     ../alpine/osdep/termout.gen.c \
+     ../alpine/osdep/termin.unx.c \
+     ../alpine/osdep/termout.unx.c \
+     ../alpine/osdep/fltrname.c \
+     ../alpine/osdep/diskquot.non.c \
+     ../alpine/osdep/execview.c \
+     ../alpine/osdep/chnge_pw.c \
+     ../alpine/osdep/mswinver.c \
+     ../alpine/osdep/jobcntrl.c \
+     ../alpine/osdep/debuging.c \
+     ../alpine/osdep/print.c \
+     ../alpine/init.c \
+     ../alpine/rpdump.c \
+     ../alpine/arg.c \
+     ../alpine/mailview.c \
+     ../alpine/keymenu.c \
+     ../alpine/dispfilt.c \
+     ../alpine/takeaddr.c \
+     ../alpine/ldapconf.c \
+     ../alpine/send.c \
+     ../alpine/radio.c \
+     ../alpine/mailcmd.c \
+     ../alpine/titlebar.c \
+     ../alpine/adrbkcmd.c \
+     ../alpine/alpine.c \
+     ../alpine/folder.c \
+     ../alpine/busy.c \
+     ../alpine/remote.c \
+     ../alpine/pipe.c \
+     ../alpine/setup.c \
+     ../alpine/after.c \
+     ../alpine/flagmaint.c \
+     ../alpine/confscroll.c \
+     ../alpine/mailindx.c \
+     ../alpine/kblock.c \
+     ../alpine/roleconf.c \
+     ../alpine/listsel.c \
+     ../alpine/status.c \
+     ../alpine/addrbook.c \
+     ../alpine/reply.c \
+     ../alpine/mailpart.c \
+     ../alpine/pattern.c \
+     ../alpine/signal.c \
+     ../alpine/rpload.c \
+     ../alpine/colorconf.c \
+     ../alpine/context.c \
+     ../alpine/pine-use.c \
+     ../alpine/imap.c \
+     ../alpine/newuser.c \
+     ../alpine/help.c \
+     ../alpine/print.c \
+     ../alpine/smime.c \
+     ../pico/osdep/mswin_tw.c \
+     ../pico/osdep/msdlg.c \
+     ../pico/osdep/read.c \
+     ../pico/osdep/chkpoint.c \
+     ../pico/osdep/fsync.c \
+     ../pico/osdep/newmail.c \
+     ../pico/osdep/getkey.c \
+     ../pico/osdep/mswin_spell.c \
+     ../pico/osdep/signals.c \
+     ../pico/osdep/shell.c \
+     ../pico/osdep/terminal.c \
+     ../pico/osdep/color.c \
+     ../pico/osdep/filesys.c \
+     ../pico/osdep/spell.c \
+     ../pico/osdep/tty.c \
+     ../pico/osdep/popen.c \
+     ../pico/osdep/truncate.c \
+     ../pico/osdep/altedit.c \
+     ../pico/osdep/mouse.c \
+     ../pico/osdep/raw.c \
+     ../pico/osdep/mswin_aspell.c \
+     ../pico/osdep/mswin.c \
+     ../pico/attach.c \
+     ../pico/display.c \
+     ../pico/basic.c \
+     ../pico/region.c \
+     ../pico/pico.c \
+     ../pico/blddate.c \
+     ../pico/browse.c \
+     ../pico/search.c \
+     ../pico/fileio.c \
+     ../pico/window.c \
+     ../pico/buffer.c \
+     ../pico/mswinver.c \
+     ../pico/word.c \
+     ../pico/bind.c \
+     ../pico/file.c \
+     ../pico/random.c \
+     ../pico/main.c \
+     ../pico/utf8stub.c \
+     ../pico/pilot.c \
+     ../pico/line.c \
+     ../pico/composer.c \
+     ../pith/charconv/filesys.c \
+     ../pith/charconv/utf8.c \
+     ../pith/osdep/temp_nam.c \
+     ../pith/osdep/fnexpand.c \
+     ../pith/osdep/domnames.c \
+     ../pith/osdep/tempfile.c \
+     ../pith/osdep/fgetpos.c \
+     ../pith/osdep/mimedisp.c \
+     ../pith/osdep/filesize.c \
+     ../pith/osdep/collate.c \
+     ../pith/osdep/err_desc.c \
+     ../pith/osdep/canonicl.c \
+     ../pith/osdep/pw_stuff.c \
+     ../pith/osdep/lstcmpnt.c \
+     ../pith/osdep/debugtime.c \
+     ../pith/osdep/rename.c \
+     ../pith/osdep/hostname.c \
+     ../pith/osdep/bldpath.c \
+     ../pith/osdep/color.c \
+     ../pith/osdep/coredump.c \
+     ../pith/osdep/canaccess.c \
+     ../pith/osdep/writ_dir.c \
+     ../pith/osdep/creatdir.c \
+     ../pith/osdep/pipe.c \
+     ../pith/mailview.c \
+     ../pith/init.c \
+     ../pith/takeaddr.c \
+     ../pith/keyword.c \
+     ../pith/text.c \
+     ../pith/conf.c \
+     ../pith/detach.c \
+     ../pith/mailcap.c \
+     ../pith/sequence.c \
+     ../pith/list.c \
+     ../pith/folder.c \
+     ../pith/icache.c \
+     ../pith/color.c \
+     ../pith/mimedesc.c \
+     ../pith/sort.c \
+     ../pith/bldaddr.c \
+     ../pith/mailindx.c \
+     ../pith/string.c \
+     ../pith/helpindx.c \
+     ../pith/ablookup.c \
+     ../pith/adjtime.c \
+     ../pith/maillist.c \
+     ../pith/escapes.c \
+     ../pith/copyaddr.c \
+     ../pith/thread.c \
+     ../pith/pattern.c \
+     ../pith/state.c \
+     ../pith/rfc2231.c \
+     ../pith/imap.c \
+     ../pith/help_h_gen.c \
+     ../pith/abdlc.c \
+     ../pith/tempfile.c \
+     ../pith/margin.c \
+     ../pith/util.c \
+     ../pith/msgno.c \
+     ../pith/send.c \
+     ../pith/charset.c \
+     ../pith/mailcmd.c \
+     ../pith/hist.c \
+     ../pith/adrbklib.c \
+     ../pith/readfile.c \
+     ../pith/news.c \
+     ../pith/editorial.c \
+     ../pith/help_c_gen.c \
+     ../pith/filter.c \
+     ../pith/mimetype.c \
+     ../pith/remote.c \
+     ../pith/store.c \
+     ../pith/pipe.c \
+     ../pith/addrstring.c \
+     ../pith/flag.c \
+     ../pith/ldap.c \
+     ../pith/status.c \
+     ../pith/addrbook.c \
+     ../pith/detoken.c \
+     ../pith/reply.c \
+     ../pith/stream.c \
+     ../pith/newmail.c \
+     ../pith/save.c \
+     ../pith/url.c \
+     ../pith/search.c \
+     ../pith/context.c \
+     ../pith/help.c \
+     ../pith/handle.c \
+     ../pith/strlst.c \
+     ../pith/smime.c \
+     ../pith/smkeys.c
 
-CATALOGS = @CATALOGS@
+CATALOGS = 
 
 # Makevars gets inserted here. (Don't remove this line!)
+# Makefile variables for PO directory in any package using GNU gettext.
+
+# Usually the message domain is the same as the package name.
+DOMAIN = $(PACKAGE)
+
+# These two variables depend on the location of this directory.
+subdir = po
+top_builddir = ..
+
+# These options get passed to xgettext.
+XGETTEXT_OPTIONS = --keyword=_ --keyword=N_
+
+# This is the copyright holder that gets inserted into the header of the
+# $(DOMAIN).pot file.  Set this to the copyright holder of the surrounding
+# package.  (Note that the msgstr strings, extracted from the package's
+# sources, belong to the copyright holder of the package.)  Translators are
+# expected to transfer the copyright for their translations to this person
+# or entity, or to disclaim their copyright.  The empty string stands for
+# the public domain; in this case the translators are expected to disclaim
+# their copyright.
+COPYRIGHT_HOLDER = Eduardo Chappa
+
+# This is the email address or URL to which the translators shall report
+# bugs in the untranslated strings:
+# - Strings which are not entire sentences, see the maintainer guidelines
+#   in the GNU gettext documentation, section 'Preparing Strings'.
+# - Strings which use unclear terms or require additional context to be
+#   understood.
+# - Strings which make invalid assumptions about notation of date, time or
+#   money.
+# - Pluralisation problems.
+# - Incorrect English spelling.
+# - Incorrect formatting.
+# It can be your email address, or a mailing list address where translators
+# can write to without being subscribed, or the URL of a web page through
+# which the translators can contact you.
+MSGID_BUGS_ADDRESS = chappa@gmx.com
+
+# This is the list of locale categories, beyond LC_MESSAGES, for which the
+# message catalogs shall be used.  It is usually empty.
+EXTRA_LOCALE_CATEGORIES =
 
 .SUFFIXES:
 .SUFFIXES: .po .gmo .mo .sed .sin .nop .po-create .po-update
@@ -392,7 +622,7 @@ $(DUMMYPOFILES):
 update-gmo: Makefile $(GMOFILES)
 	@:
 
-Makefile: Makefile.in.in Makevars $(top_builddir)/config.status @POMAKEFILEDEPS@
+Makefile: Makefile.in.in Makevars $(top_builddir)/config.status POTFILES.in
 	cd $(top_builddir) \
 	  && $(SHELL) ./config.status $(subdir)/$@.in po-directories
 
@@ -401,3 +631,50 @@ force:
 # Tell versions [3.59,3.63) of GNU make not to export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
+# Special Makefile rules for English message catalogs with quotation marks.
+
+DISTFILES.common.extra1 = quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot
+
+.SUFFIXES: .insert-header .po-update-en
+
+en@quot.po-create:
+	$(MAKE) en@quot.po-update
+en@boldquot.po-create:
+	$(MAKE) en@boldquot.po-update
+
+en@quot.po-update: en@quot.po-update-en
+en@boldquot.po-update: en@boldquot.po-update-en
+
+.insert-header.po-update-en:
+	@lang=`echo $@ | sed -e 's/\.po-update-en$$//'`; \
+	if test "$(PACKAGE)" = "gettext"; then PATH=`pwd`/../src:$$PATH; GETTEXTLIBDIR=`cd $(top_srcdir)/src && pwd`; export GETTEXTLIBDIR; fi; \
+	tmpdir=`pwd`; \
+	echo "$$lang:"; \
+	ll=`echo $$lang | sed -e 's/@.*//'`; \
+	LC_ALL=C; export LC_ALL; \
+	cd $(srcdir); \
+	if $(MSGINIT) -i $(DOMAIN).pot --no-translator -l $$ll -o - 2>/dev/null | sed -f $$tmpdir/$$lang.insert-header | $(MSGCONV) -t UTF-8 | $(MSGFILTER) sed -f `echo $$lang | sed -e 's/.*@//'`.sed 2>/dev/null > $$tmpdir/$$lang.new.po; then \
+	  if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
+	    rm -f $$tmpdir/$$lang.new.po; \
+	  else \
+	    if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
+	      :; \
+	    else \
+	      echo "creation of $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
+	      exit 1; \
+	    fi; \
+	  fi; \
+	else \
+	  echo "creation of $$lang.po failed!" 1>&2; \
+	  rm -f $$tmpdir/$$lang.new.po; \
+	fi
+
+en@quot.insert-header: insert-header.sin
+	sed -e '/^#/d' -e 's/HEADER/en@quot.header/g' $(srcdir)/insert-header.sin > en@quot.insert-header
+
+en@boldquot.insert-header: insert-header.sin
+	sed -e '/^#/d' -e 's/HEADER/en@boldquot.header/g' $(srcdir)/insert-header.sin > en@boldquot.insert-header
+
+mostlyclean: mostlyclean-quot
+mostlyclean-quot:
+	rm -f *.insert-header
